#version 460

layout(local_size_x = 16, local_size_y = 16, local_size_z = 1) in;
layout(binding = 0, set = 0, rgba16f) uniform writeonly image2D outputImage;
layout(binding = 1, set = 0, rgba16f) uniform readonly image2D inputImage;
layout(binding = 2, set = 0, rgba16f) uniform readonly image2D bloom2Image;
layout(binding = 3, set = 0, rgba16f) uniform readonly image2D bloom4Image;
layout(binding = 4, set = 0, rgba16f) uniform readonly image2D bloom6Image;


vec3 bilinearSample2(ivec2 pixel, ivec2 sourceSize, ivec2 sourcePixel) {
    vec2 sourceCoord = vec2(sourcePixel) +
        (vec2(pixel - sourcePixel) + 0.5) - 0.5;
    ivec2 base = ivec2(floor(sourceCoord));
    vec2 fraction = fract(sourceCoord);

    ivec2 lower = ivec2(0);
    ivec2 upper = sourceSize - 1;
    ivec2 p00 = clamp(base, lower, upper);
    ivec2 p10 = clamp(base + ivec2(1, 0), lower, upper);
    ivec2 p01 = clamp(base + ivec2(0, 1), lower, upper);
    ivec2 p11 = clamp(base + ivec2(1, 1), lower, upper);

    return mix(
        mix(imageLoad(bloom2Image, p00).rgb, imageLoad(bloom2Image, p10).rgb, fraction.x),
        mix(imageLoad(bloom2Image, p01).rgb, imageLoad(bloom2Image, p11).rgb, fraction.x),
        fraction.y);
}


vec3 bilinearSample4(ivec2 pixel, ivec2 sourceSize, ivec2 sourcePixel) {
    vec2 sourceCoord = vec2(sourcePixel) +
        (vec2(pixel - sourcePixel * 2) + 0.5) / 2.0 - 0.5;
    ivec2 base = ivec2(floor(sourceCoord));
    vec2 fraction = fract(sourceCoord);

    ivec2 lower = ivec2(0);
    ivec2 upper = sourceSize - 1;
    ivec2 p00 = clamp(base, lower, upper);
    ivec2 p10 = clamp(base + ivec2(1, 0), lower, upper);
    ivec2 p01 = clamp(base + ivec2(0, 1), lower, upper);
    ivec2 p11 = clamp(base + ivec2(1, 1), lower, upper);

    return mix(
        mix(imageLoad(bloom4Image, p00).rgb, imageLoad(bloom4Image, p10).rgb, fraction.x),
        mix(imageLoad(bloom4Image, p01).rgb, imageLoad(bloom4Image, p11).rgb, fraction.x),
        fraction.y);
}


vec3 bilinearSample6(ivec2 pixel, ivec2 sourceSize, ivec2 sourcePixel) {
    vec2 sourceCoord = vec2(sourcePixel) +
        (vec2(pixel - sourcePixel * 4) + 0.5) / 4.0 - 0.5;
    ivec2 base = ivec2(floor(sourceCoord));
    vec2 fraction = fract(sourceCoord);

    ivec2 lower = ivec2(0);
    ivec2 upper = sourceSize - 1;
    ivec2 p00 = clamp(base, lower, upper);
    ivec2 p10 = clamp(base + ivec2(1, 0), lower, upper);
    ivec2 p01 = clamp(base + ivec2(0, 1), lower, upper);
    ivec2 p11 = clamp(base + ivec2(1, 1), lower, upper);

    return mix(
        mix(imageLoad(bloom6Image, p00).rgb, imageLoad(bloom6Image, p10).rgb, fraction.x),
        mix(imageLoad(bloom6Image, p01).rgb, imageLoad(bloom6Image, p11).rgb, fraction.x),
        fraction.y);
}

void main() {
    ivec2 pixel = ivec2(gl_GlobalInvocationID.xy);
    ivec2 size = imageSize(outputImage);
    if (pixel.x >= size.x || pixel.y >= size.y) return;

    vec4 source = imageLoad(inputImage, pixel);
    vec3 bloom = bilinearSample2(pixel, size, pixel).rgb*0.5 + bilinearSample4(pixel, size, pixel / 2)*0.3 + bilinearSample6(pixel, size, pixel / 4)*0.2;

    imageStore(outputImage, pixel, vec4(source.rgb + bloom, source.a));
}